//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraininCourse.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscribe
    {
        public int SubscribeID { get; set; }
        public int CoursesID { get; set; }
        public int UserID { get; set; }
        public int Catalog { get; set; }
    
        public virtual Cours Cours { get; set; }
        public virtual User User { get; set; }
    }
}
